apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
env:
  APP_NAME: java-app
  UNIQUE_PREFIX: swen
  HOSTNAME: swen-java-app2.arch.beescloud.com
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://maven:3.9.6-eclipse-temurin-17
        name: build
        kind: build
        shell: sh
        run: |-
          #run mvn command
          mvn clean install
      - uses: cloudbees-io/configure-aws-credentials@v1
        name: aws-login
        id: aws-login
        with:
          aws-access-key-id: ${{ vars.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: us-east-1
          role-to-assume: cloudbees-infra-mgmt
          role-duration-seconds: "3600"
      - uses: docker://public.ecr.aws/aws-cli/aws-cli
        name: aws get call id
        run: aws sts get-caller-identity
        shell: sh
      - uses: cloudbees-io/configure-ecr-credentials@v1
        name: auth for ECR
        id: login-ecr
      - uses: cloudbees-io/kaniko@v1
        name: build docker img and push to ECR
        id: image-publish
        with:
          destination: ${{ steps.aws-login.outputs.aws-account-id
            }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.APP_NAME }}-image:${{
            env.UNIQUE_PREFIX }}-${{ cloudbees.version }}
          labels: maintainer=swen,version=1.0.1
      - uses: cloudbees-io/helm-package@v1
        name: Build and publish a helm chart
        id: helmpkg
        with:
          chart: ./charts/myapp
          version: 0.0.1
          destination: ./packaged-charts
          values: >
            image:
              repository: ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.APP_NAME }}-image
              tag: ${{ steps.image-publish.outputs.tag }}
      - uses: cloudbees-io/helm-push@v1
        name: Publish Helm chart
        id: helm-publish
        with:
          chart: ${{ steps.helmpkg.outputs.chart }}
          remote: oci://${{ steps.aws-login.outputs.aws-account-id
            }}.dkr.ecr.us-east-1.amazonaws.com
    outputs:
      chart-location: ${{ steps.helm-publish.outputs.chart }}
      chart-version: ${{ steps.helm-publish.outputs.version }}
  deploy:
    steps:
      - uses: cloudbees-io/configure-aws-credentials@v1
        name: Login AWS
        id: aws-login
        with:
          aws-access-key-id: ${{ vars.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: us-east-1
          role-to-assume: cloudbees-infra-mgmt
          role-duration-seconds: "3600"
      - uses: cloudbees-io/configure-eks-credentials@v1
        name: cloudbees-quickstart-cluster
      - uses: cloudbees-io/configure-ecr-credentials@v1
        name: login ecr
        id: login-ecr
      - uses: cloudbees-io/helm-install@v1
        name: Helm Install
        kind: deploy
        with:
          chart-location: ${{ needs.build.outputs.chart-location }}
          version: ${{ needs.build.outputs.chart-version }}
          release-name: ${{ env.UNIQUE_PREFIX }}-${{ env.APP_NAME }}
          namespace: ${{ env.UNIQUE_PREFIX }}-${{ env.APP_NAME }}
          values: |
            ingress:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: ${{ env.HOSTNAME }}
              hosts:
                - host: "${{ env.HOSTNAME }}"
                  paths:
                    - path: /
                      pathType: Prefix
                - paths:
                    - path: /
                      pathType: Prefix
    needs:
      - build
