apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://maven:3.9.6-eclipse-temurin-17
        name: Build
        kind: build
        shell: sh
        run: |-
          #run mvn command
          mvn clean install
      - uses: cloudbees-io/configure-aws-credentials@v1
        name: aws-login
        id: aws-login
        with:
          aws-access-key-id: ${{ vars.aws_access_key_id}}
          aws-secret-access-key: ${{secrets.aws_secret_access_key}}
          aws-region: us-east-1
          role-to-assume: cloudbees-infra-mgmt
      - uses: docker://public.ecr.aws/aws-cli/aws-cli
        name: aws get call id
        run: aws sts get-caller-identity
        shell: sh
      - uses: cloudbees-io/configure-ecr-credentials@v1
        name: auth for ECR
      - uses: cloudbees-io/kaniko@v1
        name: build docker img and push to ECR
        with:
          destination: ${{ steps.aws-login.outputs.aws-account-id
            }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.APP_NAME }}-image:${{
            env.UNIQUE_PREFIX }}-${{ cloudbees.version }}
